name: GitHub Readme Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Stats Card
        uses: anuraghazra/github-readme-stats@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          theme: radical
          show_icons: true
